esphome:
  name: window-actuator
  name_add_mac_suffix: true

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_secret

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

dashboard_import:
  package_import_url: github://Malte-D/window-actuator/esphome/window-actuator.yaml
  import_full_config: true

servo:
  - id: servo_movement
    output: pwm_output
    auto_detach_time: 5s
    min_level: 2.5%
    max_level: 12.5%
    transition_length: 2s
  - id: servo_handle
    output: pwm_output_2
    auto_detach_time: 5s
    min_level: 2.5%
    max_level: 12.5%
    transition_length: 3s

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D1
    frequency: 50 Hz
  - platform: esp8266_pwm
    id: pwm_output_2
    pin: D3
    frequency: 50 Hz

switch:
  - platform: gpio
    pin:
      number: D2
      mode: 
        output: true
    id: relay

cover:
  - platform: template
    id: window
    device_class: window
    name: "Window"
    open_action:
      - then:
          - switch.turn_on: relay
          - cover.template.publish:
              id: window
              current_operation: OPENING
          - servo.write:
              id: servo_handle
              level: -72%
          - delay: 3s
          - servo.write:
              id: servo_movement
              level: 68%
          - delay: 3s
          - switch.turn_off: relay
          - cover.template.publish:
              id: window
              state: OPEN
    close_action:
      - then:
          - switch.turn_on: relay
          - cover.template.publish:
              id: window
              current_operation: CLOSING
          - servo.write:
              id: servo_movement
              level: -100%
          - delay: 3s
          - servo.write:
              id: servo_handle
              level: 65%
          - delay: 3s
          - switch.turn_off: relay
          - cover.template.publish:
              id: window
              state: CLOSED
    stop_action:
      - switch.turn_off: relay
    optimistic: true
